version: '3.8'

services:

  # FastAPI Application
  api:
    build: .
    container_name: odoo_api
    hostname: odoo_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ODOO_URL=${ODOO_URL}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - odoo19_odoo19-net

  sku_check_web:
    build: ./sku_check_web
    container_name: sku_check_web
    ports:
      - "5100:5100"
    volumes:
      - ./sku_check_web:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - odoo19_odoo19-net

# volumes:
#   redis_data:

networks:
  odoo19_odoo19-net:
    external: true
